import { FunctionComponent, memo } from "react";
import TypeSingleStateNormal from "./type-single-state-normal";
import TypeChild2StateNormal from "./type-child2-state-normal";
import styled from "styled-components";

const NodesNavigationRoot = styled.div`
  margin: 0 !important;
  position: absolute;
  top: 120px;
  left: 24px;
  height: 256px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
  z-index: 3;
`;
const FormContainer: FunctionComponent = memo(() => {
  return (
    <NodesNavigationRoot>
      <TypeSingleStateNormal
        layerIcon="/layer-icon1.svg"
        nodeLayerTitle="New project"
        icon24pxActionsDeleteFat="/icon-24px--actions--delete-fat1.svg"
        icon24pxActionsShowOnFat="/icon-24px--actions--show-on-fat1.svg"
        icon24pxActionsMoreFat="/icon-24px--actions--more-fat1.svg"
        actions={false}
        action3={false}
        typeSingleStateNormalPosition="unset"
        typeSingleStateNormalWidth="272px"
      />
      <TypeChild2StateNormal
        extend="/extend1.svg"
        layerIcon="/layer-icon2.svg"
        action3
        showAction2={false}
        showIcon24pxActionsShowOn={false}
        typeChild2StateNormalPosition="unset"
        typeChild2StateNormalWidth="272px"
        typeChild2StateNormalPadding="0px var(--padding-9xs)"
        nodeLayerTitleColor="unset"
        action3BorderRadius="unset"
        action3FlexDirection="unset"
        action3Padding="unset"
        action3AlignItems="unset"
        action3JustifyContent="unset"
        action3Color="#3e3b46"
        icon24pxActionsDeleteFPosition="unset"
        icon24pxActionsDeleteFWidth="unset"
        icon24pxActionsDeleteFHeight="unset"
        icon24pxActionsDeleteFOverflow="unset"
        icon24pxActionsDeleteFFlexShrink="unset"
        icon24pxActionsDeleteFColor="#858293"
        action2BorderRadius="unset"
        action2Padding="unset"
        icon24pxActionsShowOnPosition="unset"
        icon24pxActionsShowOnWidth="unset"
        icon24pxActionsShowOnHeight="unset"
        icon24pxActionsShowOnOverflow="unset"
        icon24pxActionsShowOnFlexShrink="unset"
        icon24pxActionsShowOnBorderRadius="4px"
        icon24pxActionsShowOnFlexDirection="row"
        icon24pxActionsShowOnPadding="4px 8px"
        icon24pxActionsShowOnAlignItems="flex-start"
        icon24pxActionsShowOnJustifyContent="flex-start"
        action1BorderRadius="unset"
        action1Display="unset"
        action1FlexDirection="unset"
        action1Padding="unset"
        action1AlignItems="unset"
        action1JustifyContent="unset"
        action1Position="relative"
        action1Width="16px"
        action1Height="16px"
        action1Overflow="hidden"
        action1FlexShrink="0"
        icon24pxActionsMoreFatPosition="unset"
        icon24pxActionsMoreFatWidth="unset"
        icon24pxActionsMoreFatHeight="unset"
        icon24pxActionsMoreFatBorderRadius="4px"
        icon24pxActionsMoreFatDisplay="flex"
        icon24pxActionsMoreFatFlexDirection="row"
        icon24pxActionsMoreFatPadding="4px 8px"
        icon24pxActionsMoreFatAlignItems="center"
        icon24pxActionsMoreFatJustifyContent="flex-end"
      />
      <TypeChild2StateNormal
        extend="/extend1.svg"
        layerIcon="/layer-icon3.svg"
        nodeLayerTitle="Header (section)"
        icon24pxActionsDeleteFat="/icon-24px--actions--delete-fat1.svg"
        icon24pxActionsShowOnFat="/icon-24px--actions--show-on-fat1.svg"
        icon24pxActionsMoreFat="/icon-24px--actions--more-fat1.svg"
        actions={false}
        action3={false}
        showAction2
        showIcon24pxActionsShowOn
        typeChild2StateNormalPosition="unset"
        typeChild2StateNormalWidth="272px"
        typeChild2StateNormalPadding="0px var(--padding-9xs) 0px var(--padding-5xl)"
        nodeLayerTitleColor="#3e3b46"
        actionsFlexDirection="row"
        actionsAlignItems="center"
        actionsJustifyContent="flex-end"
        actionsLineBreak="unset"
        action3BorderRadius="4px"
        action3FlexDirection="row"
        action3Padding="4px 8px"
        action3AlignItems="flex-start"
        action3JustifyContent="flex-start"
        action3Color="unset"
        icon24pxActionsDeleteFPosition="relative"
        icon24pxActionsDeleteFWidth="16px"
        icon24pxActionsDeleteFHeight="16px"
        icon24pxActionsDeleteFOverflow="hidden"
        icon24pxActionsDeleteFFlexShrink="0"
        icon24pxActionsDeleteFColor="unset"
        action2BorderRadius="4px"
        action2Padding="4px 8px"
        icon24pxActionsShowOnPosition="relative"
        icon24pxActionsShowOnWidth="16px"
        icon24pxActionsShowOnHeight="16px"
        icon24pxActionsShowOnOverflow="hidden"
        icon24pxActionsShowOnFlexShrink="0"
        icon24pxActionsShowOnBorderRadius="unset"
        icon24pxActionsShowOnFlexDirection="unset"
        icon24pxActionsShowOnPadding="unset"
        icon24pxActionsShowOnAlignItems="unset"
        icon24pxActionsShowOnJustifyContent="unset"
        action1BorderRadius="4px"
        action1Display="flex"
        action1FlexDirection="row"
        action1Padding="4px 8px"
        action1AlignItems="center"
        action1JustifyContent="flex-end"
        action1Position="unset"
        action1Width="unset"
        action1Height="unset"
        action1Overflow="unset"
        action1FlexShrink="unset"
        icon24pxActionsMoreFatPosition="relative"
        icon24pxActionsMoreFatWidth="16px"
        icon24pxActionsMoreFatHeight="16px"
        icon24pxActionsMoreFatBorderRadius="unset"
        icon24pxActionsMoreFatDisplay="unset"
        icon24pxActionsMoreFatFlexDirection="unset"
        icon24pxActionsMoreFatPadding="unset"
        icon24pxActionsMoreFatAlignItems="unset"
        icon24pxActionsMoreFatJustifyContent="unset"
      />
      <TypeChild2StateNormal
        extend="/extend1.svg"
        layerIcon="/layer-icon4.svg"
        nodeLayerTitle="Brand bar (molecule)"
        icon24pxActionsDeleteFat="/icon-24px--actions--delete-fat1.svg"
        icon24pxActionsShowOnFat="/icon-24px--actions--show-on-fat1.svg"
        icon24pxActionsMoreFat="/icon-24px--actions--more-fat1.svg"
        actions={false}
        action3={false}
        showAction2
        showIcon24pxActionsShowOn
        typeChild2StateNormalPosition="unset"
        typeChild2StateNormalWidth="272px"
        typeChild2StateNormalPadding="0px var(--padding-9xs) 0px var(--padding-25xl)"
        nodeLayerTitleColor="#3e3b46"
        actionsFlexDirection="row"
        actionsAlignItems="center"
        actionsJustifyContent="flex-end"
        actionsLineBreak="unset"
        action3BorderRadius="4px"
        action3FlexDirection="row"
        action3Padding="4px 8px"
        action3AlignItems="flex-start"
        action3JustifyContent="flex-start"
        action3Color="unset"
        icon24pxActionsDeleteFPosition="relative"
        icon24pxActionsDeleteFWidth="16px"
        icon24pxActionsDeleteFHeight="16px"
        icon24pxActionsDeleteFOverflow="hidden"
        icon24pxActionsDeleteFFlexShrink="0"
        icon24pxActionsDeleteFColor="unset"
        action2BorderRadius="4px"
        action2Padding="4px 8px"
        icon24pxActionsShowOnPosition="relative"
        icon24pxActionsShowOnWidth="16px"
        icon24pxActionsShowOnHeight="16px"
        icon24pxActionsShowOnOverflow="hidden"
        icon24pxActionsShowOnFlexShrink="0"
        icon24pxActionsShowOnBorderRadius="unset"
        icon24pxActionsShowOnFlexDirection="unset"
        icon24pxActionsShowOnPadding="unset"
        icon24pxActionsShowOnAlignItems="unset"
        icon24pxActionsShowOnJustifyContent="unset"
        action1BorderRadius="4px"
        action1Display="flex"
        action1FlexDirection="row"
        action1Padding="4px 8px"
        action1AlignItems="center"
        action1JustifyContent="flex-end"
        action1Position="unset"
        action1Width="unset"
        action1Height="unset"
        action1Overflow="unset"
        action1FlexShrink="unset"
        icon24pxActionsMoreFatPosition="relative"
        icon24pxActionsMoreFatWidth="16px"
        icon24pxActionsMoreFatHeight="16px"
        icon24pxActionsMoreFatBorderRadius="unset"
        icon24pxActionsMoreFatDisplay="unset"
        icon24pxActionsMoreFatFlexDirection="unset"
        icon24pxActionsMoreFatPadding="unset"
        icon24pxActionsMoreFatAlignItems="unset"
        icon24pxActionsMoreFatJustifyContent="unset"
      />
      <TypeChild2StateNormal
        extend="/extend1.svg"
        layerIcon="/layer-icon5.svg"
        nodeLayerTitle="Intro screen (section)"
        icon24pxActionsDeleteFat="/icon-24px--actions--delete-fat1.svg"
        icon24pxActionsShowOnFat="/icon-24px--actions--show-on-fat1.svg"
        icon24pxActionsMoreFat="/icon-24px--actions--more-fat1.svg"
        actions={false}
        action3={false}
        showAction2
        showIcon24pxActionsShowOn
        typeChild2StateNormalPosition="unset"
        typeChild2StateNormalWidth="272px"
        typeChild2StateNormalPadding="0px var(--padding-9xs) 0px var(--padding-5xl)"
        nodeLayerTitleColor="#3e3b46"
        actionsFlexDirection="row"
        actionsAlignItems="center"
        actionsJustifyContent="flex-end"
        actionsLineBreak="unset"
        action3BorderRadius="4px"
        action3FlexDirection="row"
        action3Padding="4px 8px"
        action3AlignItems="flex-start"
        action3JustifyContent="flex-start"
        action3Color="unset"
        icon24pxActionsDeleteFPosition="relative"
        icon24pxActionsDeleteFWidth="16px"
        icon24pxActionsDeleteFHeight="16px"
        icon24pxActionsDeleteFOverflow="hidden"
        icon24pxActionsDeleteFFlexShrink="0"
        icon24pxActionsDeleteFColor="unset"
        action2BorderRadius="4px"
        action2Padding="4px 8px"
        icon24pxActionsShowOnPosition="relative"
        icon24pxActionsShowOnWidth="16px"
        icon24pxActionsShowOnHeight="16px"
        icon24pxActionsShowOnOverflow="hidden"
        icon24pxActionsShowOnFlexShrink="0"
        icon24pxActionsShowOnBorderRadius="unset"
        icon24pxActionsShowOnFlexDirection="unset"
        icon24pxActionsShowOnPadding="unset"
        icon24pxActionsShowOnAlignItems="unset"
        icon24pxActionsShowOnJustifyContent="unset"
        action1BorderRadius="4px"
        action1Display="flex"
        action1FlexDirection="row"
        action1Padding="4px 8px"
        action1AlignItems="center"
        action1JustifyContent="flex-end"
        action1Position="unset"
        action1Width="unset"
        action1Height="unset"
        action1Overflow="unset"
        action1FlexShrink="unset"
        icon24pxActionsMoreFatPosition="relative"
        icon24pxActionsMoreFatWidth="16px"
        icon24pxActionsMoreFatHeight="16px"
        icon24pxActionsMoreFatBorderRadius="unset"
        icon24pxActionsMoreFatDisplay="unset"
        icon24pxActionsMoreFatFlexDirection="unset"
        icon24pxActionsMoreFatPadding="unset"
        icon24pxActionsMoreFatAlignItems="unset"
        icon24pxActionsMoreFatJustifyContent="unset"
      />
      <TypeChild2StateNormal
        extend="/extend1.svg"
        layerIcon="/layer-icon6.svg"
        nodeLayerTitle="Text block (molecule)"
        icon24pxActionsDeleteFat="/icon-24px--actions--delete-fat1.svg"
        icon24pxActionsShowOnFat="/icon-24px--actions--show-on-fat1.svg"
        icon24pxActionsMoreFat="/icon-24px--actions--more-fat1.svg"
        actions={false}
        action3={false}
        showAction2
        showIcon24pxActionsShowOn
        typeChild2StateNormalPosition="unset"
        typeChild2StateNormalWidth="272px"
        typeChild2StateNormalPadding="0px var(--padding-9xs) 0px var(--padding-25xl)"
        nodeLayerTitleColor="#3e3b46"
        actionsFlexDirection="row"
        actionsAlignItems="center"
        actionsJustifyContent="flex-end"
        actionsLineBreak="unset"
        action3BorderRadius="4px"
        action3FlexDirection="row"
        action3Padding="4px 8px"
        action3AlignItems="flex-start"
        action3JustifyContent="flex-start"
        action3Color="unset"
        icon24pxActionsDeleteFPosition="relative"
        icon24pxActionsDeleteFWidth="16px"
        icon24pxActionsDeleteFHeight="16px"
        icon24pxActionsDeleteFOverflow="hidden"
        icon24pxActionsDeleteFFlexShrink="0"
        icon24pxActionsDeleteFColor="unset"
        action2BorderRadius="4px"
        action2Padding="4px 8px"
        icon24pxActionsShowOnPosition="relative"
        icon24pxActionsShowOnWidth="16px"
        icon24pxActionsShowOnHeight="16px"
        icon24pxActionsShowOnOverflow="hidden"
        icon24pxActionsShowOnFlexShrink="0"
        icon24pxActionsShowOnBorderRadius="unset"
        icon24pxActionsShowOnFlexDirection="unset"
        icon24pxActionsShowOnPadding="unset"
        icon24pxActionsShowOnAlignItems="unset"
        icon24pxActionsShowOnJustifyContent="unset"
        action1BorderRadius="4px"
        action1Display="flex"
        action1FlexDirection="row"
        action1Padding="4px 8px"
        action1AlignItems="center"
        action1JustifyContent="flex-end"
        action1Position="unset"
        action1Width="unset"
        action1Height="unset"
        action1Overflow="unset"
        action1FlexShrink="unset"
        icon24pxActionsMoreFatPosition="relative"
        icon24pxActionsMoreFatWidth="16px"
        icon24pxActionsMoreFatHeight="16px"
        icon24pxActionsMoreFatBorderRadius="unset"
        icon24pxActionsMoreFatDisplay="unset"
        icon24pxActionsMoreFatFlexDirection="unset"
        icon24pxActionsMoreFatPadding="unset"
        icon24pxActionsMoreFatAlignItems="unset"
        icon24pxActionsMoreFatJustifyContent="unset"
      />
      <TypeChild2StateNormal
        extend="/extend1.svg"
        layerIcon="/layer-icon7.svg"
        nodeLayerTitle="Loader (section)"
        icon24pxActionsDeleteFat="/icon-24px--actions--delete-fat1.svg"
        icon24pxActionsShowOnFat="/icon-24px--actions--show-on-fat1.svg"
        icon24pxActionsMoreFat="/icon-24px--actions--more-fat1.svg"
        actions={false}
        action3={false}
        showAction2
        showIcon24pxActionsShowOn
        typeChild2StateNormalPosition="unset"
        typeChild2StateNormalWidth="272px"
        typeChild2StateNormalPadding="0px var(--padding-9xs) 0px var(--padding-5xl)"
        nodeLayerTitleColor="#3e3b46"
        actionsFlexDirection="row"
        actionsAlignItems="center"
        actionsJustifyContent="flex-end"
        actionsLineBreak="unset"
        action3BorderRadius="4px"
        action3FlexDirection="row"
        action3Padding="4px 8px"
        action3AlignItems="flex-start"
        action3JustifyContent="flex-start"
        action3Color="unset"
        icon24pxActionsDeleteFPosition="relative"
        icon24pxActionsDeleteFWidth="16px"
        icon24pxActionsDeleteFHeight="16px"
        icon24pxActionsDeleteFOverflow="hidden"
        icon24pxActionsDeleteFFlexShrink="0"
        icon24pxActionsDeleteFColor="unset"
        action2BorderRadius="4px"
        action2Padding="4px 8px"
        icon24pxActionsShowOnPosition="relative"
        icon24pxActionsShowOnWidth="16px"
        icon24pxActionsShowOnHeight="16px"
        icon24pxActionsShowOnOverflow="hidden"
        icon24pxActionsShowOnFlexShrink="0"
        icon24pxActionsShowOnBorderRadius="unset"
        icon24pxActionsShowOnFlexDirection="unset"
        icon24pxActionsShowOnPadding="unset"
        icon24pxActionsShowOnAlignItems="unset"
        icon24pxActionsShowOnJustifyContent="unset"
        action1BorderRadius="4px"
        action1Display="flex"
        action1FlexDirection="row"
        action1Padding="4px 8px"
        action1AlignItems="center"
        action1JustifyContent="flex-end"
        action1Position="unset"
        action1Width="unset"
        action1Height="unset"
        action1Overflow="unset"
        action1FlexShrink="unset"
        icon24pxActionsMoreFatPosition="relative"
        icon24pxActionsMoreFatWidth="16px"
        icon24pxActionsMoreFatHeight="16px"
        icon24pxActionsMoreFatBorderRadius="unset"
        icon24pxActionsMoreFatDisplay="unset"
        icon24pxActionsMoreFatFlexDirection="unset"
        icon24pxActionsMoreFatPadding="unset"
        icon24pxActionsMoreFatAlignItems="unset"
        icon24pxActionsMoreFatJustifyContent="unset"
      />
      <TypeChild2StateNormal
        extend="/extend1.svg"
        layerIcon="/layer-icon8.svg"
        nodeLayerTitle="Progress bar (molecule)"
        icon24pxActionsDeleteFat="/icon-24px--actions--delete-fat1.svg"
        icon24pxActionsShowOnFat="/icon-24px--actions--show-on-fat1.svg"
        icon24pxActionsMoreFat="/icon-24px--actions--more-fat1.svg"
        actions={false}
        action3={false}
        showAction2
        showIcon24pxActionsShowOn
        typeChild2StateNormalPosition="unset"
        typeChild2StateNormalWidth="272px"
        typeChild2StateNormalPadding="0px var(--padding-9xs) 0px var(--padding-25xl)"
        nodeLayerTitleColor="#3e3b46"
        actionsFlexDirection="row"
        actionsAlignItems="center"
        actionsJustifyContent="flex-end"
        actionsLineBreak="unset"
        action3BorderRadius="4px"
        action3FlexDirection="row"
        action3Padding="4px 8px"
        action3AlignItems="flex-start"
        action3JustifyContent="flex-start"
        action3Color="unset"
        icon24pxActionsDeleteFPosition="relative"
        icon24pxActionsDeleteFWidth="16px"
        icon24pxActionsDeleteFHeight="16px"
        icon24pxActionsDeleteFOverflow="hidden"
        icon24pxActionsDeleteFFlexShrink="0"
        icon24pxActionsDeleteFColor="unset"
        action2BorderRadius="4px"
        action2Padding="4px 8px"
        icon24pxActionsShowOnPosition="relative"
        icon24pxActionsShowOnWidth="16px"
        icon24pxActionsShowOnHeight="16px"
        icon24pxActionsShowOnOverflow="hidden"
        icon24pxActionsShowOnFlexShrink="0"
        icon24pxActionsShowOnBorderRadius="unset"
        icon24pxActionsShowOnFlexDirection="unset"
        icon24pxActionsShowOnPadding="unset"
        icon24pxActionsShowOnAlignItems="unset"
        icon24pxActionsShowOnJustifyContent="unset"
        action1BorderRadius="4px"
        action1Display="flex"
        action1FlexDirection="row"
        action1Padding="4px 8px"
        action1AlignItems="center"
        action1JustifyContent="flex-end"
        action1Position="unset"
        action1Width="unset"
        action1Height="unset"
        action1Overflow="unset"
        action1FlexShrink="unset"
        icon24pxActionsMoreFatPosition="relative"
        icon24pxActionsMoreFatWidth="16px"
        icon24pxActionsMoreFatHeight="16px"
        icon24pxActionsMoreFatBorderRadius="unset"
        icon24pxActionsMoreFatDisplay="unset"
        icon24pxActionsMoreFatFlexDirection="unset"
        icon24pxActionsMoreFatPadding="unset"
        icon24pxActionsMoreFatAlignItems="unset"
        icon24pxActionsMoreFatJustifyContent="unset"
      />
    </NodesNavigationRoot>
  );
});

export default FormContainer;
